language: python
fast_finish: true

python:
  - 3.5
  - 3.6

os:
  - linux

sudo: required
dist: trusty
group: edge

notifications:
    email: false

git:
  depth: 3

# gfortran >= 6 required
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: gfortran-6

before_install:
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-6 50
  # temp for pip < 9.1
  - python -m pip -q install numpy

install: python -m pip install -e .[tests]

script: coverage run tests/test.py -v

after_success: coveralls
