language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk7

# for running tests on Travis CI container infrastructure for faster builds
sudo: true

env:
  global:
    JAVA_OPTS=-Xmx2g

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

  - sudo apt-get install build-essential git
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - git clone https://github.com/xianyi/OpenBLAS && cd OpenBLAS && sudo make && sudo make install
  - ls /opt/OpenBLAS/lib
  - sudo ln -s /opt/OpenBLAS/lib/libopenblas_haswellp-*.so /usr/lib/libblas.so.3
  - sudo ln -s /opt/OpenBLAS/lib/libopenblas_haswellp-*.so /usr/lib/liblapack.so.3
  - git clone https://github.com/deeplearning4j/nd4j
  - cd nd4j && mvn clean install -DskipTests -Dmaven.javadoc.skip=true
  - cd .. && git clone https://github.com/deeplearning4j/Canova && cd Canova && mvn clean install -DskipTests -Dmaven.javadoc.skip=true

script:
language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk7

# for running tests on Travis CI container infrastructure for faster builds
sudo: true

before_install:
  - sudo apt-get install build-essential git
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - git clone https://github.com/xianyi/OpenBLAS && cd OpenBLAS && sudo make && sudo make install
  - ls /opt/OpenBLAS/lib
  - sudo ln -s /opt/OpenBLAS/lib/libopenblas_haswellp-*.so /usr/lib/libblas.so.3
  - sudo ln -s /opt/OpenBLAS/lib/libopenblas_haswellp-*.so /usr/lib/liblapack.so.3
  - git clone https://github.com/deeplearning4j/nd4j && cd nd4j && mvn clean install -DskipTests -Dmaven.javadoc.skip=true && cd ..
  - git clone https://github.com/deeplearning4j/Canova && cd Canova && mvn clean install -DskipTests -Dmaven.javadoc.skip=true && cd ..


script:
  -  cd /home/travis/build/deeplearning4j/deeplearning4j && chmod +x ./runtests.sh && ./runtests.sh
